version: 4.0.{build}
branches:
  only:
  - main
image: Visual Studio 2022
configuration: Release
environment:
  matrix:
    - framework: netcoreapp3.1

before_build:
- ps: >-
    dotnet restore .\lib\CefSharp.Dom.sln

    New-SelfSignedCertificate -Subject "localhost" -FriendlyName "Puppeteer" -CertStoreLocation "cert:\CurrentUser\My"

    Get-ChildItem -Path cert:\CurrentUSer\my | where { $_.friendlyname -eq "Puppeteer" } | Export-Certificate -FilePath .\lib\PuppeteerSharp.TestServer\testCert.cer

build:
  project: .\lib\CefSharp.Dom.sln
  verbosity: minimal
test_script:
- cmd: >-
    cd .\lib\PuppeteerSharp.Tests

    dotnet test -f %framework% -s test.runsettings --test-adapter-path:. --logger:Appveyor
    
# Patch SDK Style `.csproj` file:
# https://www.appveyor.com/docs/build-configuration/#net-core-csproj-files-patching
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version_prefix: '{version}'
  
artifacts:
  # pushing all *.nupkg files in build directory recursively
  - path: '**\*.nupkg'
  
# Publish to myget.org feed
deploy:
  provider: NuGet
  server: https://www.myget.org/F/cefsharp/api/v2/package
  api_key:
    secure: V8du2PPvMPok3Ya701jt5v2XWQgOZf52/H5wDHXBpKvXYkIIe8sonhVUy2TmEkqt
  artifact: /.*(\.|\.s)nupkg/